name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        dotnet-version: 7.0.x

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Run mssql 2022
      run: sudo docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=StrongSAPassword$1~!" \
          -p 1433:1433 --name sql1 --hostname sql1 \
          -d \
          mcr.microsoft.com/mssql/server:2022-latest
    - name: Test
      run: dotnet test --logger html --results-directory "TestResults-${{ env.dotnet-version }}" --no-restore --configuration Release
      env:
        ConnectionStrings__DefaultConnection: Server=(localdb)\\mssqllocaldb;Database=FarmPointDb-Test;User Id=sa;Password=StrongSAPassword$1~!;
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results-${{ env.dotnet-version }}
        path: TestResults-${{ env.dotnet-version }}
      if: ${{ always() }}
