name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        dotnet-version: 7.0.x

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --logger trx --results-directory "TestResults-${{ dotnet-version }}" --no-restore --configuration Release
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results-${{ dotnet-version }}
        path: TestResults-${{ dotnet-version }}
      if: ${{ always() }}
